name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run type checking
        run: npx tsc --noEmit
        continue-on-error: true

      - name: Build project
        run: npm run build
        env:
          VITE_APP_NAME: "Verafy AI"
          VITE_DEPLOYMENT_TARGET: "vercel"
          VITE_APP_URL: ${{ github.ref == 'refs/heads/main' && 'https://verafyai.com.au' || 'https://dev.verafyai.com.au' }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Comment deployment URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ðŸš€ Deployed to Vercel: ${{ steps.deploy.outputs.url }}'
            })

      - name: Deployment summary
        run: |
          echo "### âœ… Vercel Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ”— **URL:** ${{ steps.deploy.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "ðŸŒ¿ **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ“¦ **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "â° **Time:** $(date)" >> $GITHUB_STEP_SUMMARY
